name: build

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

env:
  ATLAS_URI: ${{ secrets.ATLAS_URI }}   
  IMDB_KEY: ${{ secrets.IMDB_KEY }} 
  MAPQQUEST_KEY: ${{ secrets.MAPQQUEST_KEY }} 
  JWT_SECRET: ${{ secrets.JWT_SECRET }} 
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x,20.x]
        
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run coverage

     # Coveralls
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
    
    # SonarCloud  
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1.8 #downgraded because of bug https://github.com/orgs/community/discussions/53494
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}